name: CI

on:
  push:
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: fatton139/pr-comment-file-size@main
        with:
          dist_path: "./SkyMerchantDesktop"
          token: ${{ secrets.GITHUB_TOKEN }}