using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SkyMerchantDesktop.Services
{
    public class BazaarProductResponse
    {   
        [JsonProperty("INK_SACK:3")]
        public Bazaar? INK_SACK3 { get; set; }
        public Bazaar? BROWN_MUSHROOM { get; set; }
        public Bazaar? SPOOKY_SHARD { get; set; }

        [JsonProperty("INK_SACK:4")]
        public Bazaar? INK_SACK4 { get; set; }
        public Bazaar? TARANTULA_WEB { get; set; }
        public Bazaar? CARROT_ITEM { get; set; }
        public Bazaar? ENCHANTED_POTATO { get; set; }
        public Bazaar? EXP_BOTTLE { get; set; }
        public Bazaar? JERRY_BOX_GREEN { get; set; }
        public Bazaar? ENCHANTED_SLIME_BALL { get; set; }
        public Bazaar? ENCHANTED_GOLDEN_CARROT { get; set; }
        public Bazaar? ENCHANTED_RED_MUSHROOM { get; set; }
        public Bazaar? ENCHANTED_RABBIT_HIDE { get; set; }
        public Bazaar? FLAWED_AMETHYST_GEM { get; set; }
        public Bazaar? PERFECT_JADE_GEM { get; set; }
        public Bazaar? ENCHANTED_BIRCH_LOG { get; set; }
        public Bazaar? ENCHANTED_GUNPOWDER { get; set; }
        public Bazaar? ENCHANTED_MELON { get; set; }
        public Bazaar? ENCHANTED_SUGAR { get; set; }
        public Bazaar? CACTUS { get; set; }
        public Bazaar? ENCHANTED_BLAZE_ROD { get; set; }
        public Bazaar? FLAWED_JASPER_GEM { get; set; }
        public Bazaar? ENCHANTED_CAKE { get; set; }
        public Bazaar? PUMPKIN { get; set; }
        public Bazaar? ENCHANTED_BROWN_MUSHROOM { get; set; }
        public Bazaar? GOBLIN_EGG_YELLOW { get; set; }
        public Bazaar? WHEAT { get; set; }
        public Bazaar? FLAWED_AMBER_GEM { get; set; }
        public Bazaar? NURSE_SHARK_TOOTH { get; set; }
        public Bazaar? ENCHANTED_RAW_SALMON { get; set; }
        public Bazaar? ENCHANTED_GLISTERING_MELON { get; set; }
        public Bazaar? PRISMARINE_SHARD { get; set; }
        public Bazaar? PROTECTOR_FRAGMENT { get; set; }
        public Bazaar? ENCHANTED_EMERALD { get; set; }
        public Bazaar? ENCHANTED_SPIDER_EYE { get; set; }
        public Bazaar? RED_MUSHROOM { get; set; }
        public Bazaar? GRAND_EXP_BOTTLE { get; set; }
        public Bazaar? ENCHANTED_MELON_BLOCK { get; set; }
        public Bazaar? MUTTON { get; set; }
        public Bazaar? POWER_CRYSTAL { get; set; }
        public Bazaar? RAW_SOULFLOW { get; set; }
        public Bazaar? DIAMOND { get; set; }
        public Bazaar? SHARK_FIN { get; set; }
        public Bazaar? WISE_FRAGMENT { get; set; }
        public Bazaar? COBBLESTONE { get; set; }
        public Bazaar? REFINED_MITHRIL { get; set; }
        public Bazaar? RAW_FISH { get; set; }
        public Bazaar? SPIDER_EYE { get; set; }
        public Bazaar? PERFECT_RUBY_GEM { get; set; }
        public Bazaar? ENCHANTED_PUFFERFISH { get; set; }
        public Bazaar? YOGGIE { get; set; }
        public Bazaar? PERFECT_JASPER_GEM { get; set; }
        public Bazaar? POTATO_ITEM { get; set; }
        public Bazaar? ENCHANTED_NETHERRACK { get; set; }
        public Bazaar? ENCHANTED_HARD_STONE { get; set; }
        public Bazaar? ENCHANTED_HUGE_MUSHROOM_1 { get; set; }
        public Bazaar? REFINED_DIAMOND { get; set; }
        public Bazaar? ENCHANTED_COBBLESTONE { get; set; }
        public Bazaar? TIGHTLY_TIED_HAY_BALE { get; set; }
        public Bazaar? ENCHANTED_HUGE_MUSHROOM_2 { get; set; }
        public Bazaar? PORK { get; set; }
        public Bazaar? PRISMARINE_CRYSTALS { get; set; }
        public Bazaar? ICE { get; set; }
        public Bazaar? HUGE_MUSHROOM_1 { get; set; }
        public Bazaar? TIGER_SHARK_TOOTH { get; set; }
        public Bazaar? HUGE_MUSHROOM_2 { get; set; }
        public Bazaar? ICE_BAIT { get; set; }
        [JsonProperty("LOG_2:1")]
        public Bazaar? LOG_21 { get; set; }
        public Bazaar? ENCHANTED_SNOW_BLOCK { get; set; }
        public Bazaar? STRING { get; set; }
        public Bazaar? GOLDEN_TOOTH { get; set; }
        public Bazaar? CHEESE_FUEL { get; set; }
        public Bazaar? HYPER_CATALYST { get; set; }
        public Bazaar? RABBIT_FOOT { get; set; }
        public Bazaar? REDSTONE { get; set; }
        public Bazaar? JERRY_BOX_GOLDEN { get; set; }
        public Bazaar? PUMPKIN_GUTS { get; set; }
        public Bazaar? ENCHANTED_CACTUS_GREEN { get; set; }
        public Bazaar? BOOSTER_COOKIE { get; set; }
        public Bazaar? ENCHANTED_CARROT_ON_A_STICK { get; set; }
        public Bazaar? ENCHANTED_LAPIS_LAZULI_BLOCK { get; set; }
        public Bazaar? ENCHANTED_ENDSTONE { get; set; }
        public Bazaar? ENCHANTED_COOKIE { get; set; }
        public Bazaar? ENCHANTED_SAND { get; set; }
        public Bazaar? COLOSSAL_EXP_BOTTLE { get; set; }
        public Bazaar? ENCHANTED_STRING { get; set; }
        public Bazaar? STRONG_FRAGMENT { get; set; }
        public Bazaar? SLIME_BALL { get; set; }
        public Bazaar? ENCHANTED_ACACIA_LOG { get; set; }
        public Bazaar? SNOW_BALL { get; set; }
        public Bazaar? HOLY_FRAGMENT { get; set; }
        public Bazaar? ENCHANTED_EGG { get; set; }
        public Bazaar? SAND { get; set; }
        public Bazaar? SOUL_FRAGMENT { get; set; }
        public Bazaar? FLAWED_RUBY_GEM { get; set; }
        public Bazaar? FINE_JADE_GEM { get; set; }
        public Bazaar? RAW_CHICKEN { get; set; }
        public Bazaar? PLASMA_BUCKET { get; set; }
        public Bazaar? FLAWLESS_JASPER_GEM { get; set; }
        public Bazaar? ANCIENT_CLAW { get; set; }
        public Bazaar? ENCHANTED_LAPIS_LAZULI { get; set; }
        public Bazaar? ENCHANTED_GHAST_TEAR { get; set; }
        public Bazaar? ENCHANTED_COCOA { get; set; }
        public Bazaar? CARROT_BAIT { get; set; }
        public Bazaar? FINE_TOPAZ_GEM { get; set; }
        public Bazaar? SEEDS { get; set; }
        public Bazaar? FINE_RUBY_GEM { get; set; }
        public Bazaar? ENCHANTED_LEATHER { get; set; }
        public Bazaar? ENCHANTED_SHARK_FIN { get; set; }
        public Bazaar? ENCHANTED_SPONGE { get; set; }
        public Bazaar? PERFECT_AMBER_GEM { get; set; }
        public Bazaar? HAY_BLOCK { get; set; }
        public Bazaar? INK_SACK { get; set; }
        public Bazaar? FLINT { get; set; }
        public Bazaar? ENCHANTED_ROTTEN_FLESH { get; set; }
        public Bazaar? WOLF_TOOTH { get; set; }
        public Bazaar? ENCHANTED_SPRUCE_LOG { get; set; }
        public Bazaar? ENCHANTED_GRILLED_PORK { get; set; }
        public Bazaar? ENCHANTED_NETHER_STALK { get; set; }
        public Bazaar? ENCHANTED_REDSTONE_BLOCK { get; set; }
        public Bazaar? ENCHANTED_QUARTZ_BLOCK { get; set; }
        public Bazaar? ENCHANTED_ANCIENT_CLAW { get; set; }
        public Bazaar? GREEN_CANDY { get; set; }
        public Bazaar? ENCHANTED_REDSTONE { get; set; }
        public Bazaar? ENCHANTED_REDSTONE_LAMP { get; set; }
        public Bazaar? TREASURITE { get; set; }
        public Bazaar? DWARVEN_COMPACTOR { get; set; }
        public Bazaar? GREAT_WHITE_SHARK_TOOTH { get; set; }
        public Bazaar? GRAVEL { get; set; }
        public Bazaar? MELON { get; set; }
        public Bazaar? ENCHANTED_LAVA_BUCKET { get; set; }
        public Bazaar? ENCHANTED_PACKED_ICE { get; set; }
        [JsonProperty("RAW_FISH:3")]
        public Bazaar? RAW_FISH3 { get; set; }
        public Bazaar? ENCHANTED_PRISMARINE_SHARD { get; set; }
        public Bazaar? ENCHANTED_IRON_BLOCK { get; set; }
        public Bazaar? RECOMBOBULATOR_3000 { get; set; }
        public Bazaar? ENCHANTED_CARROT_STICK { get; set; }
        public Bazaar? BONE { get; set; }
        [JsonProperty("RAW_FISH:2")]
        public Bazaar? RAW_FISH2 { get; set; }
        [JsonProperty("RAW_FISH:1")]
        public Bazaar? RAW_FISH1 { get; set; }
        public Bazaar? REVENANT_FLESH { get; set; }
        public Bazaar? ENCHANTED_GLOWSTONE { get; set; }
        public Bazaar? ENCHANTED_PORK { get; set; }
        public Bazaar? GOBLIN_EGG_RED { get; set; }
        public Bazaar? ROUGH_JASPER_GEM { get; set; }
        public Bazaar? FEATHER { get; set; }
        public Bazaar? WHALE_BAIT { get; set; }
        public Bazaar? NETHERRACK { get; set; }
        public Bazaar? SPONGE { get; set; }
        public Bazaar? BLAZE_ROD { get; set; }
        public Bazaar? ENCHANTED_DARK_OAK_LOG { get; set; }
        public Bazaar? FLAWLESS_TOPAZ_GEM { get; set; }
        public Bazaar? YOUNG_FRAGMENT { get; set; }
        public Bazaar? ENCHANTED_CLOWNFISH { get; set; }
        public Bazaar? REFINED_MINERAL { get; set; }
        public Bazaar? ENCHANTED_GOLD { get; set; }
        public Bazaar? ENCHANTED_RAW_CHICKEN { get; set; }
        public Bazaar? ENCHANTED_WATER_LILY { get; set; }
        public Bazaar? ROUGH_AMETHYST_GEM { get; set; }
        public Bazaar? ROUGH_RUBY_GEM { get; set; }
        public Bazaar? GOBLIN_EGG_BLUE { get; set; }
        [JsonProperty("LOG:1")]
        public Bazaar? LOG1 { get; set; }
        public Bazaar? FLAWLESS_RUBY_GEM { get; set; }
        public Bazaar? NULL_ATOM { get; set; }
        public Bazaar? TITANIUM_ORE { get; set; }
        public Bazaar? CATALYST { get; set; }
        public Bazaar? BLUE_SHARK_TOOTH { get; set; }
        [JsonProperty("LOG:3")]
        public Bazaar? LOG3 { get; set; }
        [JsonProperty("LOG:2")]
        public Bazaar? LOG2 { get; set; }
        public Bazaar? BLESSED_BAIT { get; set; }
        public Bazaar? ENCHANTED_GLOWSTONE_DUST { get; set; }
        public Bazaar? ENCHANTED_INK_SACK { get; set; }
        public Bazaar? ENCHANTED_CACTUS { get; set; }
        public Bazaar? ENCHANTED_SUGAR_CANE { get; set; }
        public Bazaar? FLAWLESS_SAPPHIRE_GEM { get; set; }
        public Bazaar? ENCHANTED_COOKED_SALMON { get; set; }
        public Bazaar? ENCHANTED_SEEDS { get; set; }
        public Bazaar? CONCENTRATED_STONE { get; set; }
        public Bazaar? LOG { get; set; }
        public Bazaar? JACOBS_TICKET { get; set; }
        public Bazaar? ENCHANTED_BONE_BLOCK { get; set; }
        public Bazaar? GHAST_TEAR { get; set; }
        public Bazaar? ABSOLUTE_ENDER_PEARL { get; set; }
        public Bazaar? ENCHANTED_ENDER_PEARL { get; set; }
        public Bazaar? UNSTABLE_FRAGMENT { get; set; }
        public Bazaar? PURPLE_CANDY { get; set; }
        public Bazaar? SPIKED_BAIT { get; set; }
        public Bazaar? POLISHED_PUMPKIN { get; set; }
        public Bazaar? ENCHANTED_FERMENTED_SPIDER_EYE { get; set; }
        public Bazaar? ENCHANTED_GOLD_BLOCK { get; set; }
        public Bazaar? ROUGH_JADE_GEM { get; set; }
        public Bazaar? ENCHANTED_JUNGLE_LOG { get; set; }
        public Bazaar? ENCHANTED_FLINT { get; set; }
        public Bazaar? IRON_INGOT { get; set; }
        public Bazaar? ENCHANTED_EMERALD_BLOCK { get; set; }
        public Bazaar? NULL_OVOID { get; set; }
        public Bazaar? ENCHANTED_CLAY_BALL { get; set; }
        public Bazaar? ROUGH_SAPPHIRE_GEM { get; set; }
        public Bazaar? GLOWSTONE_DUST { get; set; }
        public Bazaar? GOLD_INGOT { get; set; }
        public Bazaar? REVENANT_VISCERA { get; set; }
        public Bazaar? PERFECT_AMETHYST_GEM { get; set; }
        public Bazaar? TARANTULA_SILK { get; set; }
        public Bazaar? TITANIC_EXP_BOTTLE { get; set; }
        public Bazaar? ENCHANTED_MUTTON { get; set; }
        public Bazaar? NULL_SPHERE { get; set; }
        public Bazaar? ENCHANTED_IRON { get; set; }
        public Bazaar? SUPER_COMPACTOR_3000 { get; set; }
        public Bazaar? SUPER_EGG { get; set; }
        public Bazaar? STOCK_OF_STONKS { get; set; }
        public Bazaar? MITHRIL_ORE { get; set; }
        public Bazaar? ENCHANTED_HAY_BLOCK { get; set; }
        public Bazaar? ENCHANTED_BONE { get; set; }
        public Bazaar? ENCHANTED_PAPER { get; set; }
        public Bazaar? ENCHANTED_TITANIUM { get; set; }
        public Bazaar? ENCHANTED_DIAMOND_BLOCK { get; set; }
        public Bazaar? SPOOKY_BAIT { get; set; }
        public Bazaar? SUPERIOR_FRAGMENT { get; set; }
        public Bazaar? MAGMA_BUCKET { get; set; }
        public Bazaar? EMERALD { get; set; }
        public Bazaar? GOBLIN_EGG_GREEN { get; set; }
        public Bazaar? ENCHANTED_RABBIT_FOOT { get; set; }
        public Bazaar? LIGHT_BAIT { get; set; }
        public Bazaar? HOT_POTATO_BOOK { get; set; }
        public Bazaar? ENCHANTED_ICE { get; set; }
        public Bazaar? CLAY_BALL { get; set; }
        public Bazaar? ARACHNE_KEEPER_FRAGMENT { get; set; }
        public Bazaar? OLD_FRAGMENT { get; set; }
        public Bazaar? GREEN_GIFT { get; set; }
        public Bazaar? WORM_MEMBRANE { get; set; }
        public Bazaar? FLAWLESS_AMETHYST_GEM { get; set; }
        public Bazaar? ROUGH_TOPAZ_GEM { get; set; }
        public Bazaar? PACKED_ICE { get; set; }
        public Bazaar? ROUGH_AMBER_GEM { get; set; }
        public Bazaar? WATER_LILY { get; set; }
        public Bazaar? LOG_2 { get; set; }
        public Bazaar? HAMSTER_WHEEL { get; set; }
        public Bazaar? ENCHANTED_OBSIDIAN { get; set; }
        public Bazaar? FINE_AMBER_GEM { get; set; }
        public Bazaar? ENCHANTED_COAL { get; set; }
        public Bazaar? ENCHANTED_QUARTZ { get; set; }
        public Bazaar? COAL { get; set; }
        public Bazaar? ENDER_PEARL { get; set; }
        public Bazaar? ENCHANTED_COAL_BLOCK { get; set; }
        public Bazaar? WEREWOLF_SKIN { get; set; }
        public Bazaar? PERFECT_TOPAZ_GEM { get; set; }
        public Bazaar? GOBLIN_EGG { get; set; }
        public Bazaar? ENCHANTED_PRISMARINE_CRYSTALS { get; set; }
        public Bazaar? DAEDALUS_STICK { get; set; }
        public Bazaar? ENCHANTED_WET_SPONGE { get; set; }
        public Bazaar? FLAWED_JADE_GEM { get; set; }
        public Bazaar? ENCHANTED_RAW_FISH { get; set; }
        public Bazaar? ENDER_STONE { get; set; }
        public Bazaar? FOUL_FLESH { get; set; }
        public Bazaar? QUARTZ { get; set; }
        public Bazaar? JERRY_BOX_PURPLE { get; set; }
        public Bazaar? RAW_BEEF { get; set; }
        public Bazaar? SLUDGE_JUICE { get; set; }
        public Bazaar? ENCHANTED_EYE_OF_ENDER { get; set; }
        public Bazaar? ECTOPLASM { get; set; }
        public Bazaar? MAGMA_CREAM { get; set; }
        public Bazaar? SUGAR_CANE { get; set; }
        public Bazaar? SHARK_BAIT { get; set; }
        public Bazaar? ENCHANTED_MITHRIL { get; set; }
        public Bazaar? RED_GIFT { get; set; }
        public Bazaar? JERRY_BOX_BLUE { get; set; }
        public Bazaar? ENCHANTED_RAW_BEEF { get; set; }
        public Bazaar? ENCHANTED_SLIME_BLOCK { get; set; }
        public Bazaar? ENCHANTED_FEATHER { get; set; }
        public Bazaar? ENCHANTED_OAK_LOG { get; set; }
        public Bazaar? RABBIT_HIDE { get; set; }
        public Bazaar? WHITE_GIFT { get; set; }
        public Bazaar? SULPHUR { get; set; }
        public Bazaar? RABBIT { get; set; }
        public Bazaar? FINE_SAPPHIRE_GEM { get; set; }
        public Bazaar? NETHER_STALK { get; set; }
        public Bazaar? DARK_BAIT { get; set; }
        public Bazaar? ENCHANTED_CARROT { get; set; }
        public Bazaar? ENCHANTED_PUMPKIN { get; set; }
        public Bazaar? GRIFFIN_FEATHER { get; set; }
        public Bazaar? ROTTEN_FLESH { get; set; }
        public Bazaar? ENCHANTED_COOKED_FISH { get; set; }
        public Bazaar? OBSIDIAN { get; set; }
        public Bazaar? SOULFLOW { get; set; }
        public Bazaar? MINNOW_BAIT { get; set; }
        public Bazaar? ENCHANTED_MAGMA_CREAM { get; set; }
        public Bazaar? ENCHANTED_FIREWORK_ROCKET { get; set; }
        public Bazaar? STARFALL { get; set; }
        public Bazaar? FLAWLESS_JADE_GEM { get; set; }
        public Bazaar? HARD_STONE { get; set; }
        public Bazaar? FLAWED_TOPAZ_GEM { get; set; }
        public Bazaar? LEATHER { get; set; }
        public Bazaar? ENCHANTED_COOKED_MUTTON { get; set; }
        public Bazaar? FINE_AMETHYST_GEM { get; set; }
        public Bazaar? REFINED_TITANIUM { get; set; }
        public Bazaar? ENCHANTED_RABBIT { get; set; }
        public Bazaar? SOUL_STRING { get; set; }
        public Bazaar? MUTANT_NETHER_STALK { get; set; }
        public Bazaar? ENCHANTED_BREAD { get; set; }
        public Bazaar? FUMING_POTATO_BOOK { get; set; }
        public Bazaar? FINE_JASPER_GEM { get; set; }
        public Bazaar? ENCHANTED_CHARCOAL { get; set; }
        public Bazaar? FLAWED_SAPPHIRE_GEM { get; set; }
        public Bazaar? FLAWLESS_AMBER_GEM { get; set; }
        public Bazaar? ENCHANTED_BLAZE_POWDER { get; set; }
        public Bazaar? SUMMONING_EYE { get; set; }
        public Bazaar? PERFECT_SAPPHIRE_GEM { get; set; }
        public Bazaar? FISH_BAIT { get; set; }
        public Bazaar? SNOW_BLOCK { get; set; }
        public Bazaar? ENCHANTED_BAKED_POTATO { get; set; }
        public Bazaar? COMPACTOR { get; set; }
        public Bazaar? ENCHANTED_DIAMOND { get; set; }
        public Bazaar? BAZAAR_COOKIE { get; set; }
    }
}
